# Generated by Django 4.0.1 on 2022-01-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gigs',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('category', models.CharField(max_length=200)),
                ('image_1', models.ImageField(default=True, null=True, upload_to='')),
                ('image_2', models.ImageField(default=True, null=True, upload_to='')),
                ('image_3', models.ImageField(default=True, null=True, upload_to='')),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
