# Generated by Django 4.0.1 on 2022-02-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_alter_gigs_created_at_alter_gigs_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='approved',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gigs',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='image_1',
            field=models.ImageField(blank=True, default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='image_2',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='image_3',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
