# Generated by Django 4.0.1 on 2022-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_gigs_approved_alter_gigs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='image_1',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
