# Generated by Django 4.0.1 on 2022-02-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_gigs_image_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigs',
            old_name='id',
            new_name='_id',
        ),
    ]
