# Generated by Django 4.0.1 on 2022-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_remove_gigs_image_1_remove_gigs_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='gigs',
            name='category',
            field=models.CharField(choices=[('data analysis', 'data analysis'), ('Advocacy & Awareness', 'Advocacy & Awareness'), ('Music / Songwriting', 'Music / Songwriting'), ('Shooting & Editing', 'Shooting & Editing'), ('sales & marketing', 'sales & marketing'), ('software development', 'software development'), ('Recruiting & Test Prep', 'Recruiting & Test Prep'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
