# Generated by Django 4.0.1 on 2022-04-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_contactform_alter_gigs_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('data analysis', 'data analysis'), ('Advocacy & Awareness', 'Advocacy & Awareness'), ('Music / Songwriting', 'Music / Songwriting'), ('Shooting & Editing', 'Shooting & Editing'), ('sales & marketing', 'sales & marketing'), ('software development', 'software development'), ('Recruiting & Test Prep', 'Recruiting & Test Prep'), ('Other', 'Other')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='gigs',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gigs.categories'),
        ),
    ]
