# Generated by Django 4.0.1 on 2022-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0015_alter_gigs_category_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='None', max_length=450),
            preserve_default=False,
        ),
    ]
